format = """\
$time \
$status\
$cmd_duration\
$line_break\
$username\
$hostname\
$directory\
$kubernetes\
$git_branch\
$git_state\
$line_break\
$battery\
$character
"""

# right_format = """\
# """

[cmd_duration]
format = '[took $duration]($style)'
disabled = false
min_time = 0
style = "dimmed white"

[directory]
read_only = " 󰌾"
truncate_to_repo = true

[status]
format = '[$symbol $status]($style)'
style = "bold red"
map_symbol = false
disabled = false

[kubernetes]
# Symbol to use before displaying the cluster context
symbol = "\u2638\ufe0f "
format = '[$symbol$context( \($namespace\))]($style) '
# The style for the module
style = "bold blue"
# Only show the current namespace when namespace is not "default"
disabled = false

[username]
format = "[$user]($style)@"

# ~/.config/starship.toml

[time]
disabled = false
use_12hr = true
format = '[\[$time\]]($style)'
time_format = '%I:%M %p'
style = "dimmed white"

[hostname]
ssh_symbol = " "

[git_commit]
style = "bg: white"
[git_state]
style = "bg: white"
[git_branch]
symbol = " "
format = "[$symbol$branch]($style)"
[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"
#[git_metrics]
#style = "bg: white"

[rust]
symbol = "󱘗 "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
